kind: Service
apiVersion: v1
metadata:
  name: php-example-service
spec:
  selector:
    app: php-example
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-example
  labels:
    app: php-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-example
  template:
    metadata:
      labels:
        app: php-example
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: php
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: phpserver-ingress
  namespace: p-756gd-pipeline
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: php-example.ok.com
    http:
      paths:
      - path:
        backend:
          serviceName: php-example-service
          servicePort: 80